### ISSUE TITLE
add health check for service

### ISSUE THREAD

**Issue by nanliu** [intelsdi-x/snap-plugin-webapi#14]

**Comment by zachary-trudo** [comment]
Hey Nan - We aren't really sure what you mean by add health check for service. Could you update with more details? Thanks

**Comment by nanliu** [comment]
I need to add some form of monitoring to our deployment to alert of us of outages, since my last trivia' change took it offline. I'll tackle this.

**Comment by nanliu** [comment]
added statuscake monitoring and wired in alerts.
